export enum ActionType {
    PageLoaded,
    Login,
    Logout,
    FilterByCategoryIds,
    FilterByCompanyIds,
    FilterByMinPrice,
    FilterByMaxPrice,
    // setMinPrice,
    // setMaxPrice,
    // UpdateCoupons,
    UpdateUsers,
    UpdateCompanies,
    UpdateCategories,
    LoadingComplete,
    EditCoupon,
    EditUser,
    EditCompany,
    EditCategory,
    resetEditedCoupon,
    resetEditedUser,
    resetEditedCompany,
    resetEditedCategory
}
